!!com.example.app.properties.PropertiesData
appiumProperties:
  platformName: android
  deviceName: device
  udid: emulator-5554
  app: D:\MobileApp\app-pendaki.apk
  automationName: UIAutomator2
  newCommandTimeout: 120
  autoGrantPermissions: true
